import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './../sass/main.scss';
import Header from "./_components/Layout/Header";
import Footer from "./_components/Layout/Footer";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
